// Package servers maps TLDs, IP ranges and query types to their WHOIS servers.
// Source: IANA root zone database via https://github.com/ocku/whois-servers
// Last updated: 2026-03 (1 000+ TLDs).
package servers

import "strings"

// Server holds the address and optional query format for a WHOIS server.
type Server struct {
	Host   string // hostname, e.g. "whois.verisign-grs.com"
	Port   int    // default 43
	Format string // query format template, %s replaced by query; default "%s\r\n"
}

func (s Server) QueryString(query string) string {
	if s.Format != "" {
		return strings.ReplaceAll(s.Format, "%s", query) + "\r\n"
	}
	return query + "\r\n"
}

func (s Server) Addr() string {
	port := s.Port
	if port == 0 {
		port = 43
	}
	return s.Host + ":" + itoa(port)
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	buf := make([]byte, 0, 10)
	for n > 0 {
		buf = append([]byte{byte('0' + n%10)}, buf...)
		n /= 10
	}
	return string(buf)
}

// plain constructs a plain server (no special query format).
func plain(host string) Server { return Server{Host: host} }

// fmted constructs a server with a custom query format (%s = query).
func fmted(host, format string) Server { return Server{Host: host, Format: format} }

// TLDServers maps TLD (lowercase, without leading dot) to WHOIS server.
// Source: IANA root zone database, updated 2026-03.
//
// Changes vs previous version:
//   ai:      whois.ai            -> whois.nic.ai
//   au:      whois.audns.net.au  -> whois.auda.org.au
//   bi:      whois.nic.bi        -> whois1.nic.bi
//   biz:     whois.biz           -> whois.nic.biz
//   cat:     whois.cat           -> whois.nic.cat
//   cc:      whois.nic.cc        -> ccwhois.verisign-grs.com
//   dk:      whois.dk-hostmaster.dk -> whois.punktum.dk
//   dm:      whois.nic.dm        -> whois.dmdomains.dm
//   hk:      whois.hkdnr.net.hk  -> whois.hkirc.hk
//   id:      whois.pandi.or.id   -> whois.id
//   ie:      whois.iedr.ie       -> whois.weare.ie
//   info:    whois.afilias.net   -> whois.nic.info
//   kg:      whois.domain.kg     -> whois.kg
//   mobi:    whois.dotmobiregistry.net -> whois.nic.mobi
//   museum:  whois.museum        -> whois.nic.museum
//   nu:      whois.nic.nu        -> whois.iis.nu
//   nz:      whois.srs.net.nz    -> whois.irs.net.nz
//   org:     whois.pir.org       -> whois.publicinterestregistry.org
//   pr:      whois.nic.pr        -> whois.afilias-srs.net
//   tr:      whois.nic.tr        -> whois.trabis.gov.tr
//   vg:      ccwhois.ksregistry.net -> whois.nic.vg
//   vu:      vunic.vu            -> whois.dnrs.vu
//
// New TLDs added: bj bm hr hu ma mk my rw sa sd se si sn tg to uz vi ye zm
// + ~700 gTLDs and IDN TLDs from IANA
var TLDServers = map[string]Server{

	// -- Infrastructure -------------------------------------------------------
	"arpa": plain("whois.iana.org"),
	"int":  plain("whois.iana.org"),

	// -- Legacy gTLDs ---------------------------------------------------------
	"com":    fmted("whois.verisign-grs.com", "domain %s"),
	"net":    fmted("whois.verisign-grs.com", "domain %s"),
	"org":    plain("whois.publicinterestregistry.org"),
	"info":   plain("whois.nic.info"),
	"biz":    plain("whois.nic.biz"),
	"name":   plain("whois.nic.name"),
	"edu":    plain("whois.educause.edu"),
	"gov":    plain("whois.dotgov.gov"),
	"mil":    plain("whois.nic.mil"),
	"mobi":   plain("whois.nic.mobi"),
	"tel":    plain("whois.nic.tel"),
	"travel": plain("whois.nic.travel"),
	"jobs":   plain("whois.nic.jobs"),
	"cat":    plain("whois.nic.cat"),
	"coop":   plain("whois.nic.coop"),
	"museum": plain("whois.nic.museum"),
	"pro":    plain("whois.nic.pro"),
	"aero":   plain("whois.aero"),
	"asia":   plain("whois.nic.asia"),
	"xxx":    plain("whois.nic.xxx"),
	"post":   plain("whois.dotpostregistry.net"),

	// -- ccTLDs ---------------------------------------------------------------
	"ac": plain("whois.nic.ac"),
	"ae": plain("whois.aeda.net.ae"),
	"af": plain("whois.nic.af"),
	"ag": plain("whois.nic.ag"),
	"ai": plain("whois.nic.ai"),
	"am": plain("whois.amnic.net"),
	"ar": plain("whois.nic.ar"),
	"as": plain("whois.nic.as"),
	"at": plain("whois.nic.at"),
	"au": plain("whois.auda.org.au"),
	"aw": plain("whois.nic.aw"),
	"ax": plain("whois.ax"),
	"be": plain("whois.dns.be"),
	"bf": plain("whois.registre.bf"),
	"bg": plain("whois.register.bg"),
	"bh": plain("whois.nic.bh"),
	"bi": plain("whois1.nic.bi"),
	"bj": plain("whois.nic.bj"),
	"bm": plain("whois.nic.bm"),
	"bn": plain("whois.bnnic.bn"),
	"bo": plain("whois.nic.bo"),
	"br": plain("whois.registro.br"),
	"bw": plain("whois.nic.net.bw"),
	"by": plain("whois.cctld.by"),
	"ca": plain("whois.cira.ca"),
	"cc": plain("ccwhois.verisign-grs.com"),
	"cd": plain("whois.nic.cd"),
	"cf": plain("whois.dot.cf"),
	"ch": plain("whois.nic.ch"),
	"ci": plain("whois.nic.ci"),
	"cl": plain("whois.nic.cl"),
	"cm": plain("whois.netcom.cm"),
	"cn": plain("whois.cnnic.cn"),
	"co": plain("whois.nic.co"),
	"cr": plain("whois.nic.cr"),
	"cv": plain("whois.nic.cv"),
	"cx": plain("whois.nic.cx"),
	"cy": plain("whois.nic.cy"),
	"cz": plain("whois.nic.cz"),
	"de": fmted("whois.denic.de", "-T dn,ace %s"),
	"dk": plain("whois.punktum.dk"),
	"dm": plain("whois.dmdomains.dm"),
	"do": plain("whois.nic.do"),
	"dz": plain("whois.nic.dz"),
	"ec": plain("whois.nic.ec"),
	"ee": plain("whois.tld.ee"),
	"eg": plain("whois.nic.eg"),
	"es": plain("whois.nic.es"),
	"et": plain("whois.ethiotelecom.et"),
	"eu": plain("whois.eu"),
	"fi": plain("whois.fi"),
	"fj": plain("www.whois.fj"),
	"fm": plain("whois.nic.fm"),
	"fo": plain("whois.nic.fo"),
	"fr": plain("whois.nic.fr"),
	"gd": plain("whois.nic.gd"),
	"ge": plain("whois.nic.ge"),
	"gf": plain("whois.mediaserv.net"),
	"gg": plain("whois.gg"),
	"gh": plain("whois.nic.gh"),
	"gi": plain("whois2.afilias-grs.net"),
	"gl": plain("whois.nic.gl"),
	"gn": plain("whois.ande.gov.gn"),
	"gp": plain("whois.nic.gp"),
	"gq": plain("whois.dominio.gq"),
	"gs": plain("whois.nic.gs"),
	"gy": plain("whois.registry.gy"),
	"hk": plain("whois.hkirc.hk"),
	"hm": plain("whois.registry.hm"),
	"hn": plain("whois.nic.hn"),
	"hr": plain("whois.dns.hr"),
	"ht": plain("whois.nic.ht"),
	"hu": plain("whois.nic.hu"),
	"id": plain("whois.id"),
	"ie": plain("whois.weare.ie"),
	"il": plain("whois.isoc.org.il"),
	"im": plain("whois.nic.im"),
	"in": plain("whois.registry.in"),
	"io": plain("whois.nic.io"),
	"iq": plain("whois.cmc.iq"),
	"ir": plain("whois.nic.ir"),
	"is": plain("whois.isnic.is"),
	"it": plain("whois.nic.it"),
	"je": plain("whois.je"),
	"jp": plain("whois.jprs.jp"),
	"ke": plain("whois.kenic.or.ke"),
	"kg": plain("whois.kg"),
	"ki": plain("whois.nic.ki"),
	"kn": plain("whois.nic.kn"),
	"kr": plain("whois.kr"),
	"ky": plain("whois.kyregistry.ky"),
	"kz": plain("whois.nic.kz"),
	"la": plain("whois.nic.la"),
	"lb": plain("whois.lbdr.org.lb"),
	"lc": plain("whois.nic.lc"),
	"li": plain("whois.nic.li"),
	"ls": plain("whois.nic.ls"),
	"lt": plain("whois.domreg.lt"),
	"lu": plain("whois.dns.lu"),
	"lv": plain("whois.nic.lv"),
	"ly": plain("whois.nic.ly"),
	"ma": plain("whois.registre.ma"),
	"md": plain("whois.nic.md"),
	"me": plain("whois.nic.me"),
	"mg": plain("whois.nic.mg"),
	"mk": plain("whois.marnet.mk"),
	"ml": plain("whois.nic.ml"),
	"mm": plain("whois.registry.gov.mm"),
	"mn": plain("whois.nic.mn"),
	"mo": plain("whois.monic.mo"),
	"mq": plain("whois.mediaserv.net"),
	"mr": plain("whois.nic.mr"),
	"ms": plain("whois.nic.ms"),
	"mu": plain("whois.nic.mu"),
	"mv": plain("whois.nic.mv"),
	"mw": plain("whois.nic.mw"),
	"mx": plain("whois.mx"),
	"my": plain("whois.mynic.my"),
	"mz": plain("whois.nic.mz"),
	"na": plain("whois.na-nic.com.na"),
	"nc": plain("whois.nc"),
	"nf": plain("whois.nic.nf"),
	"ng": plain("whois.nic.net.ng"),
	"nl": plain("whois.domain-registry.nl"),
	"no": plain("whois.norid.no"),
	"nu": plain("whois.iis.nu"),
	"nz": plain("whois.irs.net.nz"),
	"om": plain("whois.registry.om"),
	"pe": plain("kero.yachay.pe"),
	"pf": plain("whois.registry.pf"),
	"pk": plain("whois.pknic.net.pk"),
	"pl": plain("whois.dns.pl"),
	"pm": plain("whois.nic.pm"),
	"pr": plain("whois.afilias-srs.net"),
	"ps": plain("whois.pnina.ps"),
	"pt": plain("whois.dns.pt"),
	"pw": plain("whois.nic.pw"),
	"qa": plain("whois.registry.qa"),
	"re": plain("whois.nic.re"),
	"ro": plain("whois.rotld.ro"),
	"rs": plain("whois.rnids.rs"),
	"ru": plain("whois.tcinet.ru"),
	"rw": plain("whois.ricta.org.rw"),
	"sa": plain("whois.nic.net.sa"),
	"sb": plain("whois.nic.net.sb"),
	"sc": plain("whois2.afilias-grs.net"),
	"sd": plain("whois.nic.sd"),
	"se": plain("whois.iis.se"),
	"sg": plain("whois.sgnic.sg"),
	"sh": plain("whois.nic.sh"),
	"si": plain("whois.register.si"),
	"sk": plain("whois.sk-nic.sk"),
	"sm": plain("whois.nic.sm"),
	"sn": plain("whois.nic.sn"),
	"so": plain("whois.nic.so"),
	"ss": plain("whois.nic.ss"),
	"st": plain("whois.nic.st"),
	"su": plain("whois.tcinet.ru"),
	"sx": plain("whois.sx"),
	"sy": plain("whois.tld.sy"),
	"tc": plain("whois.nic.tc"),
	"td": plain("whois.nic.td"),
	"tf": plain("whois.nic.tf"),
	"tg": plain("whois.nic.tg"),
	"th": plain("whois.thnic.co.th"),
	"tk": plain("whois.dot.tk"),
	"tl": plain("whois.nic.tl"),
	"tm": plain("whois.nic.tm"),
	"tn": plain("whois.ati.tn"),
	"to": plain("whois.tonic.to"),
	"tr": plain("whois.trabis.gov.tr"),
	"tv": plain("whois.nic.tv"),
	"tw": plain("whois.twnic.net.tw"),
	"tz": plain("whois.tznic.or.tz"),
	"ua": plain("whois.ua"),
	"ug": plain("whois.co.ug"),
	"uk": plain("whois.nic.uk"),
	"us": plain("whois.nic.us"),
	"uy": plain("whois.nic.org.uy"),
	"uz": plain("whois.cctld.uz"),
	"vc": plain("whois2.afilias-grs.net"),
	"ve": plain("whois.nic.ve"),
	"vg": plain("whois.nic.vg"),
	"vi": plain("virgil.nic.vi"),
	"vu": plain("whois.dnrs.vu"),
	"wf": plain("whois.nic.wf"),
	"ws": plain("whois.website.ws"),
	"ye": plain("whois.y.net.ye"),
	"yt": plain("whois.nic.yt"),
	"zm": plain("whois.zicta.zm"),

	// -- New gTLDs -------------------------------------------------------------
	"aarp": plain("whois.nic.aarp"), "abb": plain("whois.nic.abb"),
	"abbott": plain("whois.nic.abbott"), "abbvie": plain("whois.nic.abbvie"),
	"abc": plain("whois.nic.abc"), "abogado": plain("whois.nic.abogado"),
	"abudhabi": plain("whois.nic.abudhabi"), "academy": plain("whois.nic.academy"),
	"accenture": plain("whois.nic.accenture"), "accountant": plain("whois.nic.accountant"),
	"accountants": plain("whois.nic.accountants"), "aco": plain("whois.nic.aco"),
	"actor": plain("whois.nic.actor"), "ads": plain("whois.nic.google"),
	"adult": plain("whois.nic.adult"), "aeg": plain("whois.nic.aeg"),
	"afl": plain("whois.nic.afl"), "africa": plain("whois.nic.africa"),
	"agakhan": plain("whois.nic.agakhan"), "agency": plain("whois.nic.agency"),
	"airbus": plain("whois.nic.airbus"), "airforce": plain("whois.nic.airforce"),
	"airtel": plain("whois.nic.airtel"), "akdn": plain("whois.nic.akdn"),
	"alibaba": plain("whois.nic.alibaba"), "alipay": plain("whois.nic.alipay"),
	"allfinanz": plain("whois.nic.allfinanz"), "allstate": plain("whois.nic.allstate"),
	"ally": plain("whois.nic.ally"), "alsace": plain("whois.nic.alsace"),
	"alstom": plain("whois.nic.alstom"), "amazon": plain("whois.nic.amazon"),
	"americanfamily": plain("whois.nic.americanfamily"), "amfam": plain("whois.nic.amfam"),
	"amsterdam": plain("whois.nic.amsterdam"), "android": plain("whois.nic.google"),
	"anquan": plain("whois.teleinfo.cn"), "anz": plain("whois.nic.anz"),
	"aol": plain("whois.nic.aol"), "apartments": plain("whois.nic.apartments"),
	"app": plain("whois.nic.google"), "apple": plain("whois.nic.apple"),
	"aquarelle": plain("whois.nic.aquarelle"), "arab": plain("whois.nic.arab"),
	"archi": plain("whois.nic.archi"), "army": plain("whois.nic.army"),
	"art": plain("whois.nic.art"), "arte": plain("whois.nic.arte"),
	"asda": plain("whois.nic.asda"), "associates": plain("whois.nic.associates"),
	"attorney": plain("whois.nic.attorney"), "auction": plain("whois.nic.auction"),
	"audi": plain("whois.nic.audi"), "audible": plain("whois.nic.audible"),
	"audio": plain("whois.nic.audio"), "auspost": plain("whois.nic.auspost"),
	"author": plain("whois.nic.author"), "auto": plain("whois.nic.auto"),
	"autos": plain("whois.nic.autos"), "aws": plain("whois.nic.aws"),
	"azure": plain("whois.nic.azure"), "baby": plain("whois.nic.baby"),
	"baidu": plain("whois.gtld.knet.cn"), "band": plain("whois.nic.band"),
	"bank": plain("whois.nic.bank"), "bar": plain("whois.nic.bar"),
	"barcelona": plain("whois.nic.barcelona"), "barclaycard": plain("whois.nic.barclaycard"),
	"barclays": plain("whois.nic.barclays"), "barefoot": plain("whois.nic.barefoot"),
	"bargains": plain("whois.nic.bargains"), "baseball": plain("whois.nic.baseball"),
	"basketball": plain("whois.nic.basketball"), "bauhaus": plain("whois.nic.bauhaus"),
	"bayern": plain("whois.nic.bayern"), "bbc": plain("whois.nic.bbc"),
	"bbt": plain("whois.nic.bbt"), "bbva": plain("whois.nic.bbva"),
	"bcg": plain("whois.nic.bcg"), "bcn": plain("whois.nic.bcn"),
	"beats": plain("whois.nic.beats"), "beauty": plain("whois.nic.beauty"),
	"beer": plain("whois.nic.beer"), "bentley": plain("whois.nic.bentley"),
	"berlin": plain("whois.nic.berlin"), "best": plain("whois.nic.best"),
	"bestbuy": plain("whois.nic.bestbuy"), "bet": plain("whois.nic.bet"),
	"bible": plain("whois.nic.bible"), "bid": plain("whois.nic.bid"),
	"bike": plain("whois.nic.bike"), "bing": plain("whois.nic.bing"),
	"bingo": plain("whois.nic.bingo"), "bio": plain("whois.nic.bio"),
	"black": plain("whois.nic.black"), "blackfriday": plain("whois.nic.blackfriday"),
	"blockbuster": plain("whois.nic.blockbuster"), "blog": plain("whois.nic.blog"),
	"bloomberg": plain("whois.nic.bloomberg"), "blue": plain("whois.nic.blue"),
	"bms": plain("whois.nic.bms"), "bmw": plain("whois.nic.bmw"),
	"bnpparibas": plain("whois.nic.bnpparibas"), "boats": plain("whois.nic.boats"),
	"boehringer": plain("whois.nic.boehringer"), "bofa": plain("whois.nic.bofa"),
	"bom": plain("whois.gtlds.nic.br"), "bond": plain("whois.nic.bond"),
	"boo": plain("whois.nic.google"), "book": plain("whois.nic.book"),
	"bosch": plain("whois.nic.bosch"), "bostik": plain("whois.nic.bostik"),
	"boston": plain("whois.nic.boston"), "bot": plain("whois.nic.bot"),
	"boutique": plain("whois.nic.boutique"), "box": plain("whois.nic.box"),
	"bradesco": plain("whois.nic.bradesco"), "bridgestone": plain("whois.nic.bridgestone"),
	"broadway": plain("whois.nic.broadway"), "broker": plain("whois.nic.broker"),
	"brother": plain("whois.nic.brother"), "brussels": plain("whois.nic.brussels"),
	"build": plain("whois.nic.build"), "builders": plain("whois.nic.builders"),
	"business": plain("whois.nic.business"), "buy": plain("whois.nic.buy"),
	"buzz": plain("whois.nic.buzz"), "bzh": plain("whois.nic.bzh"),
	"cab": plain("whois.nic.cab"), "cafe": plain("whois.nic.cafe"),
	"cal": plain("whois.nic.google"), "call": plain("whois.nic.call"),
	"cam": plain("whois.nic.cam"), "camera": plain("whois.nic.camera"),
	"camp": plain("whois.nic.camp"), "canon": plain("whois.nic.canon"),
	"capetown": plain("whois.nic.capetown"), "capital": plain("whois.nic.capital"),
	"capitalone": plain("whois.nic.capitalone"), "car": plain("whois.nic.car"),
	"cards": plain("whois.nic.cards"), "care": plain("whois.nic.care"),
	"career": plain("whois.nic.career"), "careers": plain("whois.nic.careers"),
	"cars": plain("whois.nic.cars"), "casa": plain("whois.nic.casa"),
	"case": plain("whois.nic.case"), "cash": plain("whois.nic.cash"),
	"casino": plain("whois.nic.casino"), "catering": plain("whois.nic.catering"),
	"catholic": plain("whois.nic.catholic"), "cba": plain("whois.nic.cba"),
	"center": plain("whois.nic.center"), "ceo": plain("whois.nic.ceo"),
	"cern": plain("whois.nic.cern"), "cfa": plain("whois.nic.cfa"),
	"cfd": plain("whois.nic.cfd"), "chanel": plain("whois.nic.chanel"),
	"channel": plain("whois.nic.google"), "charity": plain("whois.nic.charity"),
	"chat": plain("whois.nic.chat"), "cheap": plain("whois.nic.cheap"),
	"chintai": plain("whois.nic.chintai"), "christmas": plain("whois.nic.christmas"),
	"chrome": plain("whois.nic.google"), "church": plain("whois.nic.church"),
	"cipriani": plain("whois.nic.cipriani"), "circle": plain("whois.nic.circle"),
	"citadel": plain("whois.nic.citadel"), "city": plain("whois.nic.city"),
	"claims": plain("whois.nic.claims"), "cleaning": plain("whois.nic.cleaning"),
	"click": plain("whois.nic.click"), "clinic": plain("whois.nic.clinic"),
	"clinique": plain("whois.nic.clinique"), "clothing": plain("whois.nic.clothing"),
	"cloud": plain("whois.nic.cloud"), "club": plain("whois.nic.club"),
	"clubmed": plain("whois.nic.clubmed"), "coach": plain("whois.nic.coach"),
	"codes": plain("whois.nic.codes"), "coffee": plain("whois.nic.coffee"),
	"college": plain("whois.nic.college"), "cologne": plain("whois.ryce-rsp.com"),
	"commbank": plain("whois.nic.commbank"), "community": plain("whois.nic.community"),
	"company": plain("whois.nic.company"), "compare": plain("whois.nic.compare"),
	"computer": plain("whois.nic.computer"), "comsec": plain("whois.nic.comsec"),
	"condos": plain("whois.nic.condos"), "construction": plain("whois.nic.construction"),
	"consulting": plain("whois.nic.consulting"), "contact": plain("whois.nic.contact"),
	"contractors": plain("whois.nic.contractors"), "cooking": plain("whois.nic.cooking"),
	"cool": plain("whois.nic.cool"), "corsica": plain("whois.nic.corsica"),
	"country": plain("whois.nic.country"), "coupons": plain("whois.nic.coupons"),
	"courses": plain("whois.nic.courses"), "cpa": plain("whois.nic.cpa"),
	"credit": plain("whois.nic.credit"), "creditcard": plain("whois.nic.creditcard"),
	"creditunion": plain("whois.nic.creditunion"), "cricket": plain("whois.nic.cricket"),
	"crown": plain("whois.nic.crown"), "crs": plain("whois.nic.crs"),
	"cruise": plain("whois.nic.cruise"), "cruises": plain("whois.nic.cruises"),
	"cuisinella": plain("whois.nic.cuisinella"), "cymru": plain("whois.nic.cymru"),
	"cyou": plain("whois.nic.cyou"), "dabur": plain("whois.nic.dabur"),
	"dad": plain("whois.nic.google"), "dance": plain("whois.nic.dance"),
	"data": plain("whois.nic.data"), "date": plain("whois.nic.date"),
	"dating": plain("whois.nic.dating"), "datsun": plain("whois.nic.gmo"),
	"day": plain("whois.nic.google"), "dclk": plain("whois.nic.google"),
	"dds": plain("whois.nic.dds"), "deal": plain("whois.nic.deal"),
	"dealer": plain("whois.nic.dealer"), "deals": plain("whois.nic.deals"),
	"degree": plain("whois.nic.degree"), "delivery": plain("whois.nic.delivery"),
	"deloitte": plain("whois.nic.deloitte"), "delta": plain("whois.nic.delta"),
	"democrat": plain("whois.nic.democrat"), "dental": plain("whois.nic.dental"),
	"dentist": plain("whois.nic.dentist"), "desi": plain("whois.nic.desi"),
	"design": plain("whois.nic.design"), "dev": plain("whois.nic.google"),
	"diamonds": plain("whois.nic.diamonds"), "diet": plain("whois.nic.diet"),
	"digital": plain("whois.nic.digital"), "direct": plain("whois.nic.direct"),
	"directory": plain("whois.nic.directory"), "discount": plain("whois.nic.discount"),
	"dish": plain("whois.nic.dish"), "diy": plain("whois.nic.diy"),
	"dnp": plain("whois.nic.dnp"), "docs": plain("whois.nic.google"),
	"doctor": plain("whois.nic.doctor"), "dog": plain("whois.nic.dog"),
	"domains": plain("whois.nic.domains"), "dot": plain("whois.nic.dot"),
	"download": plain("whois.nic.download"), "drive": plain("whois.nic.google"),
	"dtv": plain("whois.nic.dtv"), "dubai": plain("whois.nic.dubai"),
	"dunlop": plain("whois.nic.dunlop"), "durban": plain("whois.nic.durban"),
	"dvag": plain("whois.nic.dvag"), "dvr": plain("whois.nic.dvr"),
	"earth": plain("whois.nic.earth"), "eat": plain("whois.nic.google"),
	"eco": plain("whois.nic.eco"), "edeka": plain("whois.nic.edeka"),
	"education": plain("whois.nic.education"), "email": plain("whois.nic.email"),
	"emerck": plain("whois.nic.emerck"), "energy": plain("whois.nic.energy"),
	"engineer": plain("whois.nic.engineer"), "engineering": plain("whois.nic.engineering"),
	"enterprises": plain("whois.nic.enterprises"), "epson": plain("whois.nic.epson"),
	"equipment": plain("whois.nic.equipment"), "ericsson": plain("whois.nic.ericsson"),
	"erni": plain("whois.nic.erni"), "esq": plain("whois.nic.google"),
	"estate": plain("whois.nic.estate"), "eurovision": plain("whois.nic.eurovision"),
	"eus": plain("whois.nic.eus"), "events": plain("whois.nic.events"),
	"exchange": plain("whois.nic.exchange"), "expert": plain("whois.nic.expert"),
	"exposed": plain("whois.nic.exposed"), "express": plain("whois.nic.express"),
	"extraspace": plain("whois.nic.extraspace"), "fage": plain("whois.nic.fage"),
	"fail": plain("whois.nic.fail"), "fairwinds": plain("whois.nic.fairwinds"),
	"faith": plain("whois.nic.faith"), "family": plain("whois.nic.family"),
	"fan": plain("whois.nic.fan"), "fans": plain("whois.nic.fans"),
	"farm": plain("whois.nic.farm"), "fashion": plain("whois.nic.fashion"),
	"fast": plain("whois.nic.fast"), "fedex": plain("whois.nic.fedex"),
	"feedback": plain("whois.nic.feedback"), "ferrari": plain("whois.nic.ferrari"),
	"fidelity": plain("whois.nic.fidelity"), "fido": plain("whois.nic.fido"),
	"film": plain("whois.nic.film"), "final": plain("whois.gtlds.nic.br"),
	"finance": plain("whois.nic.finance"), "financial": plain("whois.nic.financial"),
	"fire": plain("whois.nic.fire"), "firestone": plain("whois.nic.firestone"),
	"firmdale": plain("whois.nic.firmdale"), "fish": plain("whois.nic.fish"),
	"fishing": plain("whois.nic.fishing"), "fit": plain("whois.nic.fit"),
	"fitness": plain("whois.nic.fitness"), "flights": plain("whois.nic.flights"),
	"florist": plain("whois.nic.florist"), "flowers": plain("whois.nic.flowers"),
	"fly": plain("whois.nic.google"), "foo": plain("whois.nic.google"),
	"football": plain("whois.nic.football"), "forex": plain("whois.nic.forex"),
	"forsale": plain("whois.nic.forsale"), "forum": plain("whois.nic.forum"),
	"foundation": plain("whois.nic.foundation"), "fox": plain("whois.nic.fox"),
	"free": plain("whois.nic.free"), "fresenius": plain("whois.nic.fresenius"),
	"frl": plain("whois.nic.frl"), "frogans": plain("whois.nic.frogans"),
	"fujitsu": plain("whois.nic.gmo"), "fun": plain("whois.nic.fun"),
	"fund": plain("whois.nic.fund"), "furniture": plain("whois.nic.furniture"),
	"futbol": plain("whois.nic.futbol"), "fyi": plain("whois.nic.fyi"),
	"gal": plain("whois.nic.gal"), "gallery": plain("whois.nic.gallery"),
	"gallo": plain("whois.nic.gallo"), "gallup": plain("whois.nic.gallup"),
	"game": plain("whois.nic.game"), "games": plain("whois.nic.games"),
	"garden": plain("whois.nic.garden"), "gay": plain("whois.nic.gay"),
	"gbiz": plain("whois.nic.google"), "gdn": plain("whois.nic.gdn"),
	"gea": plain("whois.nic.gea"), "gent": plain("whois.nic.gent"),
	"genting": plain("whois.nic.genting"), "george": plain("whois.nic.george"),
	"ggee": plain("whois.nic.ggee"), "gift": plain("whois.uniregistry.net"),
	"gifts": plain("whois.nic.gifts"), "gives": plain("whois.nic.gives"),
	"giving": plain("whois.nic.giving"), "glass": plain("whois.nic.glass"),
	"gle": plain("whois.nic.google"), "global": plain("whois.nic.global"),
	"globo": plain("whois.gtlds.nic.br"), "gmail": plain("whois.nic.google"),
	"gmbh": plain("whois.nic.gmbh"), "gmo": plain("whois.nic.gmo"),
	"gmx": plain("whois.nic.gmx"), "godaddy": plain("whois.nic.godaddy"),
	"gold": plain("whois.nic.gold"), "goldpoint": plain("whois.nic.goldpoint"),
	"golf": plain("whois.nic.golf"), "goo": plain("whois.nic.gmo"),
	"goodyear": plain("whois.nic.goodyear"), "goog": plain("whois.nic.google"),
	"google": plain("whois.nic.google"), "gop": plain("whois.nic.gop"),
	"got": plain("whois.nic.got"), "graphics": plain("whois.nic.graphics"),
	"gratis": plain("whois.nic.gratis"), "green": plain("whois.nic.green"),
	"gripe": plain("whois.nic.gripe"), "grocery": plain("whois.nic.grocery"),
	"group": plain("whois.nic.group"), "gucci": plain("whois.nic.gucci"),
	"guge": plain("whois.nic.google"), "guide": plain("whois.nic.guide"),
	"guitars": plain("whois.nic.guitars"), "guru": plain("whois.nic.guru"),
	"hair": plain("whois.nic.hair"), "hamburg": plain("whois.nic.hamburg"),
	"hangout": plain("whois.nic.google"), "haus": plain("whois.nic.haus"),
	"hdfc": plain("whois.nic.hdfc"), "hdfcbank": plain("whois.nic.hdfcbank"),
	"healthcare": plain("whois.nic.healthcare"), "help": plain("whois.nic.help"),
	"helsinki": plain("whois.nic.helsinki"), "here": plain("whois.nic.google"),
	"hermes": plain("whois.nic.hermes"), "hiphop": plain("whois.nic.hiphop"),
	"hisamitsu": plain("whois.nic.gmo"), "hitachi": plain("whois.nic.gmo"),
	"hiv": plain("whois.nic.hiv"), "hkt": plain("whois.nic.hkt"),
	"hockey": plain("whois.nic.hockey"), "holdings": plain("whois.nic.holdings"),
	"holiday": plain("whois.nic.holiday"), "homedepot": plain("whois.nic.homedepot"),
	"homes": plain("whois.nic.homes"), "honda": plain("whois.nic.honda"),
	"horse": plain("whois.nic.horse"), "hospital": plain("whois.nic.hospital"),
	"host": plain("whois.nic.host"), "hosting": plain("whois.nic.hosting"),
	"hot": plain("whois.nic.hot"), "hotels": plain("whois.nic.hotels"),
	"hotmail": plain("whois.nic.hotmail"), "house": plain("whois.nic.house"),
	"how": plain("whois.nic.google"), "hughes": plain("whois.nic.hughes"),
	"hyundai": plain("whois.nic.hyundai"), "ibm": plain("whois.nic.ibm"),
	"icbc": plain("whois.nic.icbc"), "ice": plain("whois.nic.ice"),
	"icu": plain("whois.nic.icu"), "ifm": plain("whois.nic.ifm"),
	"ikano": plain("whois.nic.ikano"), "imamat": plain("whois.nic.imamat"),
	"imdb": plain("whois.nic.imdb"), "immo": plain("whois.nic.immo"),
	"immobilien": plain("whois.nic.immobilien"), "inc": plain("whois.nic.inc"),
	"industries": plain("whois.nic.industries"), "infiniti": plain("whois.nic.gmo"),
	"ing": plain("whois.nic.google"), "ink": plain("whois.nic.ink"),
	"institute": plain("whois.nic.institute"), "insurance": plain("whois.nic.insurance"),
	"insure": plain("whois.nic.insure"), "international": plain("whois.nic.international"),
	"investments": plain("whois.nic.investments"), "irish": plain("whois.nic.irish"),
	"ismaili": plain("whois.nic.ismaili"), "ist": plain("whois.nic.ist"),
	"istanbul": plain("whois.nic.istanbul"), "itv": plain("whois.nic.itv"),
	"jaguar": plain("whois.nic.jaguar"), "java": plain("whois.nic.java"),
	"jcb": plain("whois.nic.gmo"), "jeep": plain("whois.nic.jeep"),
	"jetzt": plain("whois.nic.jetzt"), "jewelry": plain("whois.nic.jewelry"),
	"jio": plain("whois.nic.jio"), "jll": plain("whois.nic.jll"),
	"joburg": plain("whois.nic.joburg"), "jot": plain("whois.nic.jot"),
	"joy": plain("whois.nic.joy"), "juegos": plain("whois.uniregistry.net"),
	"juniper": plain("whois.nic.juniper"), "kaufen": plain("whois.nic.kaufen"),
	"kddi": plain("whois.nic.kddi"), "kerryhotels": plain("whois.nic.kerryhotels"),
	"kerrylogistics": plain("whois.nic.kerrylogistics"), "kerryproperties": plain("whois.nic.kerryproperties"),
	"kfh": plain("whois.nic.kfh"), "kia": plain("whois.nic.kia"),
	"kids": plain("whois.nic.kids"), "kim": plain("whois.nic.kim"),
	"kindle": plain("whois.nic.kindle"), "kitchen": plain("whois.nic.kitchen"),
	"kiwi": plain("whois.nic.kiwi"), "koeln": plain("whois.ryce-rsp.com"),
	"komatsu": plain("whois.nic.komatsu"), "kosher": plain("whois.nic.kosher"),
	"krd": plain("whois.nic.krd"), "kuokgroup": plain("whois.nic.kuokgroup"),
	"kyoto": plain("whois.nic.kyoto"), "lacaixa": plain("whois.nic.lacaixa"),
	"lamborghini": plain("whois.nic.lamborghini"), "lamer": plain("whois.nic.lamer"),
	"lancaster": plain("whois.nic.lancaster"), "land": plain("whois.nic.land"),
	"landrover": plain("whois.nic.landrover"), "lasalle": plain("whois.nic.lasalle"),
	"lat": plain("whois.nic.lat"), "latino": plain("whois.nic.latino"),
	"latrobe": plain("whois.nic.latrobe"), "law": plain("whois.nic.law"),
	"lawyer": plain("whois.nic.lawyer"), "lds": plain("whois.nic.lds"),
	"lease": plain("whois.nic.lease"), "leclerc": plain("whois.nic.leclerc"),
	"lefrak": plain("whois.nic.lefrak"), "legal": plain("whois.nic.legal"),
	"lego": plain("whois.nic.lego"), "lexus": plain("whois.nic.lexus"),
	"lgbt": plain("whois.nic.lgbt"), "lidl": plain("whois.nic.lidl"),
	"life": plain("whois.nic.life"), "lifeinsurance": plain("whois.nic.lifeinsurance"),
	"lifestyle": plain("whois.nic.lifestyle"), "lighting": plain("whois.nic.lighting"),
	"like": plain("whois.nic.like"), "limited": plain("whois.nic.limited"),
	"limo": plain("whois.nic.limo"), "link": plain("whois.uniregistry.net"),
	"lipsy": plain("whois.nic.lipsy"), "live": plain("whois.nic.live"),
	"llc": plain("whois.nic.llc"), "llp": plain("whois.nic.llp"),
	"loan": plain("whois.nic.loan"), "loans": plain("whois.nic.loans"),
	"locker": plain("whois.nic.locker"), "locus": plain("whois.nic.locus"),
	"lol": plain("whois.nic.lol"), "london": plain("whois.nic.london"),
	"lotte": plain("whois.nic.lotte"), "lotto": plain("whois.nic.lotto"),
	"love": plain("whois.nic.love"), "lpl": plain("whois.nic.lpl"),
	"lplfinancial": plain("whois.nic.lplfinancial"), "ltd": plain("whois.nic.ltd"),
	"ltda": plain("whois.nic.ltda"), "lundbeck": plain("whois.nic.lundbeck"),
	"luxe": plain("whois.nic.luxe"), "luxury": plain("whois.nic.luxury"),
	"madrid": plain("whois.nic.madrid"), "maif": plain("whois.nic.maif"),
	"maison": plain("whois.nic.maison"), "makeup": plain("whois.nic.makeup"),
	"man": plain("whois.nic.man"), "management": plain("whois.nic.management"),
	"mango": plain("whois.nic.mango"), "map": plain("whois.nic.google"),
	"market": plain("whois.nic.market"), "marketing": plain("whois.nic.marketing"),
	"markets": plain("whois.nic.markets"), "marriott": plain("whois.nic.marriott"),
	"mba": plain("whois.nic.mba"), "mckinsey": plain("whois.nic.mckinsey"),
	"med": plain("whois.nic.med"), "media": plain("whois.nic.media"),
	"meet": plain("whois.nic.google"), "melbourne": plain("whois.nic.melbourne"),
	"meme": plain("whois.nic.google"), "memorial": plain("whois.nic.memorial"),
	"men": plain("whois.nic.men"), "menu": plain("whois.nic.menu"),
	"merckmsd": plain("whois.nic.merckmsd"), "miami": plain("whois.nic.miami"),
	"microsoft": plain("whois.nic.microsoft"), "mini": plain("whois.nic.mini"),
	"mit": plain("whois.nic.mit"), "mitsubishi": plain("whois.nic.gmo"),
	"mls": plain("whois.nic.mls"), "mma": plain("whois.nic.mma"),
	"mobile": plain("whois.nic.mobile"), "moda": plain("whois.nic.moda"),
	"moe": plain("whois.nic.moe"), "moi": plain("whois.nic.moi"),
	"mom": plain("whois.nic.mom"), "monash": plain("whois.nic.monash"),
	"money": plain("whois.nic.money"), "monster": plain("whois.nic.monster"),
	"mormon": plain("whois.nic.mormon"), "mortgage": plain("whois.nic.mortgage"),
	"moscow": plain("whois.nic.moscow"), "moto": plain("whois.nic.moto"),
	"motorcycles": plain("whois.nic.motorcycles"), "mov": plain("whois.nic.google"),
	"movie": plain("whois.nic.movie"), "msd": plain("whois.nic.msd"),
	"mtn": plain("whois.nic.mtn"), "mtr": plain("whois.nic.mtr"),
	"music": plain("whois.nic.music"), "nab": plain("whois.nic.nab"),
	"nagoya": plain("whois.nic.nagoya"), "natura": plain("whois.gtlds.nic.br"),
	"navy": plain("whois.nic.navy"), "nec": plain("whois.nic.nec"),
	"netbank": plain("whois.nic.netbank"), "network": plain("whois.nic.network"),
	"new": plain("whois.nic.google"), "news": plain("whois.nic.news"),
	"next": plain("whois.nic.next"), "nextdirect": plain("whois.nic.nextdirect"),
	"nexus": plain("whois.nic.google"), "ngo": plain("whois.nic.ngo"),
	"nhk": plain("whois.nic.nhk"), "nico": plain("whois.nic.nico"),
	"nikon": plain("whois.nic.nikon"), "ninja": plain("whois.nic.ninja"),
	"nissan": plain("whois.nic.gmo"), "nissay": plain("whois.nic.nissay"),
	"nokia": plain("whois.nic.nokia"), "norton": plain("whois.nic.norton"),
	"now": plain("whois.nic.now"), "nowruz": plain("whois.nic.nowruz"),
	"nowtv": plain("whois.nic.nowtv"), "nra": plain("whois.nic.nra"),
	"nrw": plain("whois.nic.nrw"), "nyc": plain("whois.nic.nyc"),
	"obi": plain("whois.nic.obi"), "observer": plain("whois.nic.observer"),
	"office": plain("whois.nic.office"), "okinawa": plain("whois.nic.okinawa"),
	"olayan": plain("whois.nic.olayan"), "olayangroup": plain("whois.nic.olayangroup"),
	"ollo": plain("whois.nic.ollo"), "omega": plain("whois.nic.omega"),
	"one": plain("whois.nic.one"), "ong": plain("whois.nic.ong"),
	"onl": plain("whois.nic.onl"), "online": plain("whois.nic.online"),
	"ooo": plain("whois.nic.ooo"), "open": plain("whois.nic.open"),
	"oracle": plain("whois.nic.oracle"), "orange": plain("whois.nic.orange"),
	"organic": plain("whois.nic.organic"), "origins": plain("whois.nic.origins"),
	"osaka": plain("whois.nic.osaka"), "otsuka": plain("whois.nic.otsuka"),
	"ott": plain("whois.nic.ott"), "ovh": plain("whois.nic.ovh"),
	"page": plain("whois.nic.google"), "panasonic": plain("whois.nic.gmo"),
	"paris": plain("whois.nic.paris"), "pars": plain("whois.nic.pars"),
	"partners": plain("whois.nic.partners"), "parts": plain("whois.nic.parts"),
	"party": plain("whois.nic.party"), "pay": plain("whois.nic.pay"),
	"pccw": plain("whois.nic.pccw"), "pet": plain("whois.nic.pet"),
	"pharmacy": plain("whois.nic.pharmacy"), "phd": plain("whois.nic.google"),
	"philips": plain("whois.nic.philips"), "phone": plain("whois.nic.phone"),
	"photo": plain("whois.nic.photo"), "photography": plain("whois.nic.photography"),
	"photos": plain("whois.nic.photos"), "physio": plain("whois.nic.physio"),
	"pics": plain("whois.nic.pics"), "pictet": plain("whois.nic.pictet"),
	"pictures": plain("whois.nic.pictures"), "pid": plain("whois.nic.pid"),
	"pin": plain("whois.nic.pin"), "ping": plain("whois.nic.ping"),
	"pink": plain("whois.nic.pink"), "pioneer": plain("whois.nic.pioneer"),
	"pizza": plain("whois.nic.pizza"), "place": plain("whois.nic.place"),
	"play": plain("whois.nic.google"), "playstation": plain("whois.nic.playstation"),
	"plumbing": plain("whois.nic.plumbing"), "plus": plain("whois.nic.plus"),
	"pnc": plain("whois.nic.pnc"), "pohl": plain("whois.nic.pohl"),
	"poker": plain("whois.nic.poker"), "politie": plain("whois.nic.politie"),
	"porn": plain("whois.nic.porn"), "press": plain("whois.nic.press"),
	"prime": plain("whois.nic.prime"), "prod": plain("whois.nic.google"),
	"productions": plain("whois.nic.productions"), "prof": plain("whois.nic.google"),
	"progressive": plain("whois.nic.progressive"), "promo": plain("whois.nic.promo"),
	"properties": plain("whois.nic.properties"), "property": plain("whois.nic.property"),
	"protection": plain("whois.nic.protection"), "pub": plain("whois.nic.pub"),
	"pwc": plain("whois.nic.pwc"), "qpon": plain("whois.nic.qpon"),
	"quebec": plain("whois.nic.quebec"), "quest": plain("whois.nic.quest"),
	"racing": plain("whois.nic.racing"), "radio": plain("whois.nic.radio"),
	"read": plain("whois.nic.read"), "realestate": plain("whois.nic.realestate"),
	"realtor": plain("whois.nic.realtor"), "realty": plain("whois.nic.realty"),
	"recipes": plain("whois.nic.recipes"), "red": plain("whois.nic.red"),
	"redstone": plain("whois.nic.redstone"), "redumbrella": plain("whois.nic.redumbrella"),
	"rehab": plain("whois.nic.rehab"), "reise": plain("whois.nic.reise"),
	"reisen": plain("whois.nic.reisen"), "reit": plain("whois.nic.reit"),
	"reliance": plain("whois.nic.reliance"), "ren": plain("whois.nic.ren"),
	"rent": plain("whois.nic.rent"), "rentals": plain("whois.nic.rentals"),
	"repair": plain("whois.nic.repair"), "report": plain("whois.nic.report"),
	"republican": plain("whois.nic.republican"), "rest": plain("whois.nic.rest"),
	"restaurant": plain("whois.nic.restaurant"), "review": plain("whois.nic.review"),
	"reviews": plain("whois.nic.reviews"), "rexroth": plain("whois.nic.rexroth"),
	"rich": plain("whois.nic.rich"), "richardli": plain("whois.nic.richardli"),
	"ricoh": plain("whois.nic.ricoh"), "ril": plain("whois.nic.ril"),
	"rio": plain("whois.gtlds.nic.br"), "rip": plain("whois.nic.rip"),
	"rocks": plain("whois.nic.rocks"), "rodeo": plain("whois.nic.rodeo"),
	"rogers": plain("whois.nic.rogers"), "room": plain("whois.nic.room"),
	"rsvp": plain("whois.nic.google"), "rugby": plain("whois.nic.rugby"),
	"ruhr": plain("whois.nic.ruhr"), "run": plain("whois.nic.run"),
	"rwe": plain("whois.nic.rwe"), "ryukyu": plain("whois.nic.ryukyu"),
	"saarland": plain("whois.nic.saarland"), "safe": plain("whois.nic.safe"),
	"safety": plain("whois.nic.safety"), "sale": plain("whois.nic.sale"),
	"salon": plain("whois.nic.salon"), "samsclub": plain("whois.nic.samsclub"),
	"samsung": plain("whois.nic.samsung"), "sandvik": plain("whois.nic.sandvik"),
	"sandvikcoromant": plain("whois.nic.sandvikcoromant"), "sanofi": plain("whois.nic.sanofi"),
	"sap": plain("whois.nic.sap"), "sarl": plain("whois.nic.sarl"),
	"save": plain("whois.nic.save"), "saxo": plain("whois.nic.saxo"),
	"sbi": plain("whois.nic.sbi"), "sbs": plain("whois.nic.sbs"),
	"scb": plain("whois.nic.scb"), "schaeffler": plain("whois.afilias-srs.net"),
	"schmidt": plain("whois.nic.schmidt"), "scholarships": plain("whois.nic.scholarships"),
	"school": plain("whois.nic.school"), "schule": plain("whois.nic.schule"),
	"schwarz": plain("whois.nic.schwarz"), "science": plain("whois.nic.science"),
	"scot": plain("whois.nic.scot"), "search": plain("whois.nic.google"),
	"seat": plain("whois.nic.seat"), "secure": plain("whois.nic.secure"),
	"security": plain("whois.nic.security"), "seek": plain("whois.nic.seek"),
	"select": plain("whois.nic.select"), "services": plain("whois.nic.services"),
	"seven": plain("whois.nic.seven"), "sew": plain("whois.nic.sew"),
	"sex": plain("whois.nic.sex"), "sexy": plain("whois.nic.sexy"),
	"sfr": plain("whois.nic.sfr"), "shangrila": plain("whois.nic.shangrila"),
	"sharp": plain("whois.nic.gmo"), "shaw": plain("whois.afilias-srs.net"),
	"shell": plain("whois.nic.shell"), "shia": plain("whois.nic.shia"),
	"shiksha": plain("whois.nic.shiksha"), "shoes": plain("whois.nic.shoes"),
	"shop": plain("whois.nic.shop"), "shopping": plain("whois.nic.shopping"),
	"shouji": plain("whois.teleinfo.cn"), "show": plain("whois.nic.show"),
	"silk": plain("whois.nic.silk"), "sina": plain("whois.nic.sina"),
	"singles": plain("whois.nic.singles"), "site": plain("whois.nic.site"),
	"ski": plain("whois.nic.ski"), "skin": plain("whois.nic.skin"),
	"sky": plain("whois.nic.sky"), "skype": plain("whois.nic.skype"),
	"sling": plain("whois.nic.sling"), "smart": plain("whois.nic.smart"),
	"smile": plain("whois.nic.smile"), "sncf": plain("whois.nic.sncf"),
	"soccer": plain("whois.nic.soccer"), "social": plain("whois.nic.social"),
	"softbank": plain("whois.nic.softbank"), "software": plain("whois.nic.software"),
	"solar": plain("whois.nic.solar"), "solutions": plain("whois.nic.solutions"),
	"sony": plain("whois.nic.sony"), "soy": plain("whois.nic.google"),
	"spa": plain("whois.nic.spa"), "space": plain("whois.nic.space"),
	"sport": plain("whois.nic.sport"), "spot": plain("whois.nic.spot"),
	"srl": plain("whois.nic.srl"), "stada": plain("whois.nic.stada"),
	"star": plain("whois.nic.star"), "statebank": plain("whois.nic.statebank"),
	"stc": plain("whois.nic.stc"), "stcgroup": plain("whois.nic.stcgroup"),
	"stockholm": plain("whois.nic.stockholm"), "storage": plain("whois.nic.storage"),
	"store": plain("whois.nic.store"), "stream": plain("whois.nic.stream"),
	"studio": plain("whois.nic.studio"), "study": plain("whois.nic.study"),
	"style": plain("whois.nic.style"), "sucks": plain("whois.nic.sucks"),
	"supplies": plain("whois.nic.supplies"), "supply": plain("whois.nic.supply"),
	"support": plain("whois.nic.support"), "surf": plain("whois.nic.surf"),
	"surgery": plain("whois.nic.surgery"), "suzuki": plain("whois.nic.suzuki"),
	"swatch": plain("whois.nic.swatch"), "swiss": plain("whois.nic.swiss"),
	"sydney": plain("whois.nic.sydney"), "systems": plain("whois.nic.systems"),
	"tab": plain("whois.nic.tab"), "taipei": plain("whois.nic.taipei"),
	"talk": plain("whois.nic.talk"), "taobao": plain("whois.nic.taobao"),
	"tatamotors": plain("whois.nic.tatamotors"), "tatar": plain("whois.nic.tatar"),
	"tattoo": plain("whois.nic.tattoo"), "tax": plain("whois.nic.tax"),
	"taxi": plain("whois.nic.taxi"), "tci": plain("whois.nic.tci"),
	"tdk": plain("whois.nic.tdk"), "team": plain("whois.nic.team"),
	"tech": plain("whois.nic.tech"), "technology": plain("whois.nic.technology"),
	"temasek": plain("whois.nic.temasek"), "tennis": plain("whois.nic.tennis"),
	"teva": plain("whois.nic.teva"), "thd": plain("whois.nic.thd"),
	"theater": plain("whois.nic.theater"), "theatre": plain("whois.nic.theatre"),
	"tiaa": plain("whois.nic.tiaa"), "tickets": plain("whois.nic.tickets"),
	"tienda": plain("whois.nic.tienda"), "tips": plain("whois.nic.tips"),
	"tires": plain("whois.nic.tires"), "tirol": plain("whois.nic.tirol"),
	"tmall": plain("whois.nic.tmall"), "today": plain("whois.nic.today"),
	"tokyo": plain("whois.nic.tokyo"), "tools": plain("whois.nic.tools"),
	"top": plain("whois.nic.top"), "toray": plain("whois.nic.toray"),
	"toshiba": plain("whois.nic.toshiba"), "total": plain("whois.nic.total"),
	"tours": plain("whois.nic.tours"), "town": plain("whois.nic.town"),
	"toyota": plain("whois.nic.toyota"), "toys": plain("whois.nic.toys"),
	"trade": plain("whois.nic.trade"), "trading": plain("whois.nic.trading"),
	"training": plain("whois.nic.training"), "travelers": plain("whois.nic.travelers"),
	"travelersinsurance": plain("whois.nic.travelersinsurance"),
	"trust": plain("whois.nic.trust"), "trv": plain("whois.nic.trv"),
	"tube": plain("whois.nic.tube"), "tui": plain("whois.nic.tui"),
	"tunes": plain("whois.nic.tunes"), "tushu": plain("whois.nic.tushu"),
	"tvs": plain("whois.nic.tvs"), "ubank": plain("whois.nic.ubank"),
	"ubs": plain("whois.nic.ubs"), "unicom": plain("whois.nic.unicom"),
	"university": plain("whois.nic.university"), "uno": plain("whois.nic.uno"),
	"uol": plain("whois.gtlds.nic.br"), "ups": plain("whois.nic.ups"),
	"vacations": plain("whois.nic.vacations"), "vana": plain("whois.nic.vana"),
	"vanguard": plain("whois.nic.vanguard"), "vegas": plain("whois.nic.vegas"),
	"ventures": plain("whois.nic.ventures"), "verisign": plain("whois.nic.verisign"),
	"versicherung": plain("whois.nic.versicherung"), "vet": plain("whois.nic.vet"),
	"viajes": plain("whois.nic.viajes"), "video": plain("whois.nic.video"),
	"vig": plain("whois.nic.vig"), "viking": plain("whois.nic.viking"),
	"villas": plain("whois.nic.villas"), "vin": plain("whois.nic.vin"),
	"vip": plain("whois.nic.vip"), "virgin": plain("whois.nic.virgin"),
	"visa": plain("whois.nic.visa"), "vision": plain("whois.nic.vision"),
	"viva": plain("whois.nic.viva"), "vlaanderen": plain("whois.nic.vlaanderen"),
	"vodka": plain("whois.nic.vodka"), "volvo": plain("whois.nic.volvo"),
	"vote": plain("whois.nic.vote"), "voting": plain("whois.nic.voting"),
	"voto": plain("whois.nic.voto"), "voyage": plain("whois.nic.voyage"),
	"wales": plain("whois.nic.wales"), "walmart": plain("whois.nic.walmart"),
	"walter": plain("whois.nic.walter"), "wang": plain("whois.gtld.knet.cn"),
	"wanggou": plain("whois.nic.wanggou"), "watch": plain("whois.nic.watch"),
	"watches": plain("whois.nic.watches"), "webcam": plain("whois.nic.webcam"),
	"weber": plain("whois.nic.weber"), "website": plain("whois.nic.website"),
	"wed": plain("whois.nic.wed"), "wedding": plain("whois.nic.wedding"),
	"weibo": plain("whois.nic.weibo"), "weir": plain("whois.nic.weir"),
	"whoswho": plain("whois.nic.whoswho"), "wien": plain("whois.nic.wien"),
	"wiki": plain("whois.nic.wiki"), "win": plain("whois.nic.win"),
	"windows": plain("whois.nic.windows"), "wine": plain("whois.nic.wine"),
	"wme": plain("whois.nic.wme"), "wolterskluwer": plain("whois.nic.wolterskluwer"),
	"woodside": plain("whois.nic.woodside"), "work": plain("whois.nic.work"),
	"works": plain("whois.nic.works"), "world": plain("whois.nic.world"),
	"wow": plain("whois.nic.wow"), "wtc": plain("whois.nic.wtc"),
	"wtf": plain("whois.nic.wtf"), "xbox": plain("whois.nic.xbox"),
	"xerox": plain("whois.nic.xerox"), "xihuan": plain("whois.teleinfo.cn"),
	"xin": plain("whois.nic.xin"), "xyz": plain("whois.nic.xyz"),
	"yachts": plain("whois.nic.yachts"), "yamaxun": plain("whois.nic.yamaxun"),
	"yoga": plain("whois.nic.yoga"), "yokohama": plain("whois.nic.yokohama"),
	"you": plain("whois.nic.you"), "youtube": plain("whois.nic.google"),
	"yun": plain("whois.teleinfo.cn"), "zappos": plain("whois.nic.zappos"),
	"zara": plain("whois.nic.zara"), "zip": plain("whois.nic.google"),
	"zone": plain("whois.nic.zone"), "zuerich": plain("whois.nic.zuerich"),

	// -- IDN TLDs (punycode) --------------------------------------------------
	"xn--11b4c3d": plain("whois.nic.xn--11b4c3d"), "xn--1qqw23a": plain("whois.ngtld.cn"),
	"xn--2scrj9c": plain("whois.registry.in"), "xn--30rr7y": plain("whois.gtld.knet.cn"),
	"xn--3bst00m": plain("whois.gtld.knet.cn"), "xn--3ds443g": plain("whois.teleinfo.cn"),
	"xn--3e0b707e": plain("whois.kr"), "xn--3hcrj9c": plain("whois.registry.in"),
	"xn--3pxu8k": plain("whois.nic.xn--3pxu8k"), "xn--42c2d9a": plain("whois.nic.xn--42c2d9a"),
	"xn--45br5cyl": plain("whois.registry.in"), "xn--45brj9c": plain("whois.registry.in"),
	"xn--45q11c": plain("whois.gtld.knet.cn"), "xn--4dbrk0ce": plain("whois.isoc.org.il"),
	"xn--4gbrim": plain("whois.nic.xn--4gbrim"), "xn--55qw42g": plain("whois.conac.cn"),
	"xn--55qx5d": plain("whois.ngtld.cn"), "xn--5su34j936bgsg": plain("whois.nic.xn--5su34j936bgsg"),
	"xn--5tzm5g": plain("whois.nic.xn--5tzm5g"), "xn--6frz82g": plain("whois.nic.xn--6frz82g"),
	"xn--6qq986b3xl": plain("whois.gtld.knet.cn"), "xn--80adxhks": plain("whois.nic.xn--80adxhks"),
	"xn--80ao21a": plain("whois.nic.kz"), "xn--80aqecdr1a": plain("whois.nic.xn--80aqecdr1a"),
	"xn--80asehdb": plain("whois.nic.xn--80asehdb"), "xn--80aswg": plain("whois.nic.xn--80aswg"),
	"xn--8y0a063a": plain("whois.nic.xn--8y0a063a"), "xn--90a3ac": plain("whois.rnids.rs"),
	"xn--90ae": plain("whois.imena.bg"), "xn--90ais": plain("whois.cctld.by"),
	"xn--9dbq2a": plain("whois.nic.xn--9dbq2a"), "xn--9et52u": plain("whois.gtld.knet.cn"),
	"xn--9krt00a": plain("whois.nic.xn--9krt00a"), "xn--b4w605ferd": plain("whois.nic.xn--b4w605ferd"),
	"xn--c1avg": plain("whois.nic.xn--c1avg"), "xn--c2br7g": plain("whois.nic.xn--c2br7g"),
	"xn--cckwcxetd": plain("whois.nic.xn--cckwcxetd"), "xn--cg4bki": plain("whois.kr"),
	"xn--clchc0ea0b2g2a9gcd": plain("whois.ta.sgnic.sg"), "xn--czrs0t": plain("whois.nic.xn--czrs0t"),
	"xn--czru2d": plain("whois.gtld.knet.cn"), "xn--d1acj3b": plain("whois.nic.xn--d1acj3b"),
	"xn--d1alf": plain("whois.marnet.mk"), "xn--e1a4c": plain("whois.eu"),
	"xn--efvy88h": plain("whois.nic.xn--efvy88h"), "xn--fhbei": plain("whois.nic.xn--fhbei"),
	"xn--fiq228c5hs": plain("whois.teleinfo.cn"), "xn--fiq64b": plain("whois.gtld.knet.cn"),
	"xn--fiqs8s": plain("cwhois.cnnic.cn"), "xn--fiqz9s": plain("cwhois.cnnic.cn"),
	"xn--fjq720a": plain("whois.nic.xn--fjq720a"), "xn--flw351e": plain("whois.nic.google"),
	"xn--fpcrj9c3d": plain("whois.registry.in"), "xn--fzys8d69uvgm": plain("whois.nic.xn--fzys8d69uvgm"),
	"xn--gecrj9c": plain("whois.registry.in"), "xn--h2breg3eve": plain("whois.registry.in"),
	"xn--h2brj9c": plain("whois.registry.in"), "xn--h2brj9c8c": plain("whois.registry.in"),
	"xn--hxt814e": plain("whois.gtld.knet.cn"), "xn--i1b6b1a6a2e": plain("whois.nic.xn--i1b6b1a6a2e"),
	"xn--io0a7i": plain("whois.ngtld.cn"), "xn--j1aef": plain("whois.nic.xn--j1aef"),
	"xn--j1amh": plain("whois.dotukr.com"), "xn--j6w193g": plain("whois.hkirc.hk"),
	"xn--jlq480n2rg": plain("whois.nic.xn--jlq480n2rg"), "xn--kcrx77d1x4a": plain("whois.nic.xn--kcrx77d1x4a"),
	"xn--kprw13d": plain("whois.twnic.net.tw"), "xn--kpry57d": plain("whois.twnic.net.tw"),
	"xn--kput3i": plain("whois.nic.xn--kput3i"), "xn--lgbbat1ad8j": plain("whois.nic.dz"),
	"xn--mgb9awbf": plain("whois.registry.om"), "xn--mgba3a4f16a": plain("whois.nic.ir"),
	"xn--mgba7c0bbn0a": plain("whois.nic.xn--mgba7c0bbn0a"), "xn--mgbaam7a8h": plain("whois.aeda.net.ae"),
	"xn--mgbab2bd": plain("whois.nic.xn--mgbab2bd"), "xn--mgbah1a3hjkrd": plain("whois.nic.mr"),
	"xn--mgbbh1a": plain("whois.registry.in"), "xn--mgbbh1a71e": plain("whois.registry.in"),
	"xn--mgbca7dzdo": plain("whois.nic.xn--mgbca7dzdo"), "xn--mgberp4a5d4ar": plain("whois.nic.net.sa"),
	"xn--mgbgu82a": plain("whois.registry.in"), "xn--mgbi4ecexp": plain("whois.nic.xn--mgbi4ecexp"),
	"xn--mgbt3dhd": plain("whois.nic.xn--mgbt3dhd"), "xn--mgbtx2b": plain("whois.cmc.iq"),
	"xn--mgbx4cd0ab": plain("whois.mynic.my"), "xn--mix891f": plain("whois.monic.mo"),
	"xn--mk1bu44c": plain("whois.nic.xn--mk1bu44c"), "xn--mxtq1m": plain("whois.nic.xn--mxtq1m"),
	"xn--ngbc5azd": plain("whois.nic.xn--ngbc5azd"), "xn--ngbe9e0a": plain("whois.nic.xn--ngbe9e0a"),
	"xn--ngbrx": plain("whois.nic.xn--ngbrx"), "xn--node": plain("whois.itdc.ge"),
	"xn--nqv7f": plain("whois.nic.xn--nqv7f"), "xn--nqv7fs00ema": plain("whois.nic.xn--nqv7fs00ema"),
	"xn--o3cw4h": plain("whois.thnic.co.th"), "xn--ogbpf8fl": plain("whois.tld.sy"),
	"xn--p1acf": plain("whois.nic.xn--p1acf"), "xn--p1ai": plain("whois.tcinet.ru"),
	"xn--pgbs0dh": plain("whois.ati.tn"), "xn--pssy2u": plain("whois.nic.xn--pssy2u"),
	"xn--q7ce6a": plain("whois.nic.la"), "xn--q9jyb4c": plain("whois.nic.google"),
	"xn--qcka1pmc": plain("whois.nic.google"), "xn--qxa6a": plain("whois.eu"),
	"xn--rvc1e0am3e": plain("whois.registry.in"), "xn--s9brj9c": plain("whois.registry.in"),
	"xn--ses554g": plain("whois.nic.xn--ses554g"), "xn--t60b56a": plain("whois.nic.xn--t60b56a"),
	"xn--tckwe": plain("whois.nic.xn--tckwe"), "xn--tiq49xqyj": plain("whois.nic.xn--tiq49xqyj"),
	"xn--unup4y": plain("whois.nic.xn--unup4y"),
	"xn--vermgensberater-ctb": plain("whois.nic.xn--vermgensberater-ctb"),
	"xn--vermgensberatung-pwb": plain("whois.nic.xn--vermgensberatung-pwb"),
	"xn--vhquv": plain("whois.nic.xn--vhquv"), "xn--vuq861b": plain("whois.teleinfo.cn"),
	"xn--w4r85el8fhu5dnra": plain("whois.nic.xn--w4r85el8fhu5dnra"),
	"xn--w4rs40l": plain("whois.nic.xn--w4rs40l"), "xn--wgbl6a": plain("whois.registry.qa"),
	"xn--xhq521b": plain("whois.ngtld.cn"), "xn--xkc2dl3a5ee0h": plain("whois.registry.in"),
	"xn--y9a3aq": plain("whois.amnic.net"), "xn--yfro4i67o": plain("whois.zh.sgnic.sg"),
	"xn--ygbi2ammx": plain("whois.pnina.ps"), "xn--zfr164b": plain("whois.conac.cn"),
}

// RIRServers maps RIR names to their WHOIS server.
var RIRServers = map[string]Server{
	"afrinic": plain("whois.afrinic.net"),
	"apnic":   plain("whois.apnic.net"),
	"arin":    plain("whois.arin.net"),
	"lacnic":  plain("whois.lacnic.net"),
	"ripe":    plain("whois.ripe.net"),
}

// IANAServer is the fallback used to discover which WHOIS server to use.
var IANAServer = Server{Host: "whois.iana.org"}

// ASNServer is the default server for AS number lookups.
var ASNServer = Server{Host: "whois.arin.net"}

// ForDomain returns the WHOIS server for a given domain name.
// It strips subdomains and resolves by TLD, falling back to IANA.
// IANA itself will return a refer: for any valid TLD, so the fallback
// is always safe.
func ForDomain(domain string) Server {
	parts := strings.Split(strings.ToLower(domain), ".")
	// Try two-level TLD first (e.g. co.uk, com.au), then single TLD
	if len(parts) >= 3 {
		twoLevel := parts[len(parts)-2] + "." + parts[len(parts)-1]
		if s, ok := TLDServers[twoLevel]; ok {
			return s
		}
	}
	if len(parts) >= 2 {
		tld := parts[len(parts)-1]
		if s, ok := TLDServers[tld]; ok {
			return s
		}
	}
	return IANAServer
}
